### ISSUE TITLE
Homebrew doesn't have recipe `firefox`

### ISSUE THREAD

**Issue by nils-werner** [browsh-org/homebrew-browsh#1]
In your recipe [you say](https://github.com/browsh-org/homebrew-browsh/blob/master/browsh.rb#L8)

    depends_on "firefox"

which makes the installation fail, because there exists no such Homebrew formula. However, they have a Cask:

    depends_on cask: "firefox"

If you do this and use Firefox from a Cask, you need to start browsh using

    browsh -firefox /usr/local/Caskroom/firefox/latest/Firefox.app/Contents/MacOS/firefox

**Comment by tombh** [comment]
I never replied in over 4 years!!! I'm so sorry. I think this is fixed now, because I just mention the Firefox dependency in the `caveats:` section.
